const products = [
    {id: 1, name: 'Жигулевское',img: '../images/products/beer/boiler/Ю.Факел светлое.png'},
    {id: 2, name: 'Союзное бойлерное',img: '../images/products/beer/boiler/Пиво союзное бойлерное фильт. банка.png'},
    {id: 3, name: 'Чешское бойлерное',img: '../images/products/beer/boiler/Чешское бойлерное банка.png'},
    {id: 4, name: 'Сладовар безалк.',img: '../images/products/beer/cupping/Сладовар безалк..png'},
    {id: 5, name: 'Совпиво',img: '../images/products/beer/cupping/Совпиво.png'},
    {id: 6, name: 'Шихан светлое',img: '../images/products/beer/cupping/Шихан светлое.png'},
    {id: 7, name: 'Сладовар cristall',img: '../images/products/beer/glass/Сладовар cristall.png'},
    {id: 8, name: 'Сладовар пшеничное',img: '../images/products/beer/glass/Сладовар пшеничное.png'},
    {id: 9, name: 'Irish Ale ирландский эль',img: '../images/products/beer/glass/Irish Ale ирландский эль.png'},
    {id: 10, name: 'Weissberg безалк.',img: '../images/products/beer/glass/Weissberg безалк..png'},
    {id: 11, name: 'Weissberg Вишня',img: '../images/products/beer/glass/Weissberg Вишня.png'},
    {id: 12, name: 'Weissberg Малина',img: '../images/products/beer/glass/Weissberg Малина.png'},
    {id: 13, name: 'Dunkelberg темное',img: '../images/products/beer/glass/Dunkelberg темное.png'},
    {id: 14, name: 'Сухумское Свет.фильт',img: '../images/products/beer/glass/Сухумское Свет.фильт.png'},
    {id: 15, name: 'Медный вишня',img: '../images/products/beer/glass/Медный вишня.png'},
    {id: 16, name: 'Медный грейпфрут',img: '../images/products/beer/glass/Медный грейпфрут.png'},
    {id: 17, name: 'Медный малина',img: '../images/products/beer/glass/Медный малина.png'},
    {id: 18, name: 'Медный жигулевское',img: '../images/products/beer/glass/Медный жигулевское.png'},
    {id: 19, name: 'Алтайский колос светлое',img: '../images/products/beer/glass/Алтайский колос светлое.png'},
    {id: 20, name: 'Апшеронское авторское',img: '../images/products/beer/glass/Апшеронское авторское.png'},
    {id: 21, name: 'Апшеронское светлое',img: '../images/products/beer/glass/Апшеронское светлое.png'},
    {id: 22, name: 'Асбир гост фильт.',img: '../images/products/beer/glass/Асбир гост фильт..png'},
    {id: 23, name: 'Афипское пиво',img: '../images/products/beer/glass/Афипское пиво.png'},
    {id: 24, name: 'Афипское премиум',img: '../images/products/beer/glass/Афипское премиум.png'},
    {id: 25, name: 'Бархатное темное',img: '../images/products/beer/glass/Бархатное темное.png'},
    {id: 26, name: 'Белореченское',img: '../images/products/beer/glass/Белореченское.png'},
    {id: 27, name: 'Бойлерное с азотом',img: '../images/products/beer/glass/Бойлерное с азотом.png'},
    {id: 28, name: 'Динское жигулевское',img: '../images/products/beer/glass/Динское жигулевское.png'},
    {id: 29, name: 'Динское Станичное',img: '../images/products/beer/glass/Динское Станичное.png'},
    {id: 30, name: 'Динское Чешское',img: '../images/products/beer/glass/Динское Чешское.png'},
    {id: 31, name: 'Динское',img: '../images/products/beer/glass/Динское.png'},
    {id: 32, name: 'Жигулевское',img: '../images/products/beer/glass/Жигулевское.png'},
    {id: 33, name: 'Золото Хакасии светлое',img: '../images/products/beer/glass/Золото Хакасии светлое.png'},
    {id: 34, name: 'Каспийсое мягкое',img: '../images/products/beer/glass/Каспийсое мягкое.png'},
    {id: 35, name: 'Кроп Жигулевское',img: '../images/products/beer/glass/Кроп Жигулевское.png'},
    {id: 36, name: 'Кроп светлое фильт.',img: '../images/products/beer/glass/Кроп светлое фильт..png'},
    {id: 37, name: 'Крым lager',img: '../images/products/beer/glass/Крым lager.png'},
    {id: 38, name: 'Крым безалк.',img: '../images/products/beer/glass/Крым безалк..png'},
    {id: 39, name: 'Крым жигулевское',img: '../images/products/beer/glass/Крым жигулевское.png'},
    {id: 40, name: 'Крым светлое',img: '../images/products/beer/glass/Крым светлое.png'},
    {id: 41, name: 'Крым темное',img: '../images/products/beer/glass/Крым темное.png'},
    {id: 42, name: 'Крымский мост',img: '../images/products/beer/glass/Крымский мост.png'},
    {id: 43, name: 'Марочное светлое',img: '../images/products/beer/glass/Марочное светлое.png'},
    {id: 44, name: 'Майкопское 0%',img: '../images/products/beer/glass/Майкопское 0%.png'},
    {id: 45, name: 'Медведь особое светлое фильт.',img: '../images/products/beer/glass/Медведь особое светлое фильт..png'},
    {id: 46, name: 'Немецкое классическое',img: '../images/products/beer/glass/Немецкое классическое.png'},
    {id: 47, name: 'Немецкое светлое',img: '../images/products/beer/glass/Немецкое светлое.png'},
    {id: 48, name: 'Новосибирское фирменное светлое',img: '../images/products/beer/glass/Новосибирское фирменное светлое.png'},
    {id: 49, name: 'Регион 23',img: '../images/products/beer/glass/Регион 23.png'},
    {id: 50, name: 'Рыбацкое светлое',img: '../images/products/beer/glass/Рыбацкое светлое.png'},
    {id: 51, name: 'Симферопольское светлое',img: '../images/products/beer/glass/Симферопольское светлое.png'},
    {id: 52, name: 'Томское фирменное',img: '../images/products/beer/glass/Томское фирменное.png'},
    {id: 53, name: 'Чешское светлое фильт.',img: '../images/products/beer/glass/Чешское светлое фильт..png'},
    {id: 54, name: 'Чешское',img: '../images/products/beer/glass/Чешское.png'},
    {id: 55, name: 'Шумерское',img: '../images/products/beer/glass/Шумерское.png'},
];